spring:
  datasource: #cloud
    url: jdbc:postgresql://dpg-cvnnml24d50c73d0hrtg-a.singapore-postgres.render.com/placify_db_vl78
    username: mj_finalyear
    password: RaqaBR7bTjhfYTlZMv70Jw8z90596QDI

#    url: jdbc:postgresql://localhost:5432/placify_local
#    username: postgres
#    password: murali27#
  jpa:
    show-sql: true
  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com

    port: 587
    username: expensetracker.nsm.projectet@gmail.com
    password: fqsa klma ceku bzyk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

dev:
  domain-url: localhost:8080/api/v0
  fromMail: expensetracker.nsm.projectet@gmail.com
  key: "Nm5uMjdvb3gwYmluMTB3c3FpaGVuNDZ6dWdscTQ4ZzduZTN3OGt0eXpvYnM3bGtpdndlamNiOG5qd282bmw2dnJ3aHJyZGJvNm1haWZkcmlkZXl2eDFxbWJ2cDBtOXVmeGJrbGx2Zjlpanoxd3NhZDJ6Nmc3ZDFzbXpnbjZkMmQ="

logging:
  level:
    org.quartz.impl.jdbcjobstore: DEBUG
    org.quartz.impl.jdbcjobstore.PostgreSQLDelegate: DEBUG
    org.quartz.impl.jdbcjobstore.JobStoreSupport: DEBUG